Занятие 3, задача 1
js-tasks-ru/jsbasic-20220124_al45 pull request #6
Opened 2022-02-04 23:33 UTC by lacondeguy

2022-02-04 23:34 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-02-05 00:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-02-05 00:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-02-05 18:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-02-06 06:20 UTC, koalex requested changes
Исправить `2-3` и `3-1` (см. комментарии)

2022-02-06 06:20 UTC, koalex commented on 2-module/3-task/index.js
> +    calculator.a = a;
Неправильно. Нужно решить эту задачу через `this` и обычной функцией, а не стрелочной. Надо исправить.

2022-02-06 06:20 UTC, koalex commented on 3-module/1-task/index.js
> +  result.push(users[i].name);
Нужно решить эту задачу через метод `map`. Исправить.

2022-02-07 05:45 UTC, koalex approved these changes

2022-02-07 05:45 UTC, merged